### ISSUE TITLE
Angular 1.6

### ISSUE THREAD

**Issue by HLNAJAM** [alexcrack/angular-ui-notification#112] opened 2017-01-12 10:42 UTC
There is an issue I am facing when using notifications with angular 1.6.

![capture](https://cloud.githubusercontent.com/assets/21244627/21886450/99b65d90-d8dd-11e6-8981-2606f4cf2841.PNG)

This maybe because angular 1.6 does not support success and error methods anymore. Is there any work around?

**Comment by alexcrack** [comment] 2017-01-12 11:23
This is a duplicate of #106.
Issue has been fixed in version v0.3.5. Please update library.

**Closed by alexcrack** 2017-01-12 11:23 UTC
